services:
  application:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DB_URL: jdbc:postgresql://database:5432/schoolMagazine
      SPRING_DB_USERNAME: postgres
      SPRING_DB_PASSWORD: 12345
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: schoolMagazine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/schoolMagazine.sql:/docker-entrypoint-initdb.d/schoolMagazine.sql:ro
volumes:
  pgdata:
